[tool.poetry]
name = "dummy"
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
scikit-learn = "1.3"
yellowbrick = "1.5"
pandas = "2.1.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
